// Готовые схемы тренировок - БОЕВАЯ ВЕРСИЯ

export type WorkoutScheme = {
  id: string;
  name: string;
  russianName: string; // понятное название на русском
  description: string;
  daysPerWeek: number;
  minMinutes: number; // минимальная рекомендуемая длительность
  maxMinutes: number; // максимальная рекомендуемая длительность
  splitType: string;
  experienceLevels: string[];
  goals: string[];
  equipmentRequired: string[];
  dayLabels: Array<{ day: number; label: string; focus: string }>;
  benefits: string[];
  notes?: string;
  intensity: "low" | "moderate" | "high"; // интенсивность
  targetSex?: "male" | "female" | "any"; // для кого больше подходит
};

export const workoutSchemes: WorkoutScheme[] = [
  // ============= 2 ДНЯ В НЕДЕЛЮ =============
  {
    id: "full_body_2x_beginner",
    name: "Full Body Starter",
    russianName: "Начинающий: Всё тело",
    description: "Две базовые тренировки на всё тело — идеальный старт для новичков",
    daysPerWeek: 2,
    minMinutes: 30,
    maxMinutes: 60,
    splitType: "full_body",
    experienceLevels: ["beginner"],
    goals: ["health_wellness", "lose_weight", "athletic_body"],
    equipmentRequired: ["gym_full", "dumbbells", "bodyweight"],
    dayLabels: [
      { day: 1, label: "Full Body A", focus: "Базовые движения: приседания, жимы, тяги на все тело" },
      { day: 2, label: "Full Body B", focus: "Вариации базы с фокусом на другие углы и мышцы" },
    ],
    benefits: [
      "Простая структура — легко запомнить",
      "Комфортное восстановление — 2-3 дня между тренировками",
      "Каждая мышца работает 2 раза в неделю — оптимально для роста",
    ],
    notes: "Подходит для тех, кто только начинает свой фитнес-путь",
    intensity: "low",
    targetSex: "any",
  },
  {
    id: "full_body_2x_recovery",
    name: "Full Body Recovery",
    russianName: "После перерыва",
    description: "Восстановительная программа после долгого перерыва",
    daysPerWeek: 2,
    minMinutes: 30,
    maxMinutes: 60,
    splitType: "full_body",
    experienceLevels: ["beginner"],
    goals: ["health_wellness", "lose_weight"],
    equipmentRequired: ["gym_full", "dumbbells"],
    dayLabels: [
      { day: 1, label: "Full Body Gentle", focus: "Мягкая нагрузка, восстановление техники" },
      { day: 2, label: "Full Body Rebuild", focus: "Постепенное увеличение интенсивности" },
    ],
    benefits: [
      "Щадящая нагрузка для восстановления после перерыва",
      "Фокус на технике и нейромышечной связи",
      "Минимальный риск травм и перетренированности",
    ],
    intensity: "low",
    targetSex: "any",
  },

  // ============= 3 ДНЯ В НЕДЕЛЮ =============
  {
    id: "full_body_3x_classic",
    name: "Full Body Classic",
    russianName: "Классика на всё тело",
    description: "Классика — три полноценные тренировки на всё тело",
    daysPerWeek: 3,
    minMinutes: 45,
    maxMinutes: 75,
    splitType: "full_body",
    experienceLevels: ["beginner", "beginner", "intermediate"],
    goals: ["build_muscle", "athletic_body", "lose_weight", "health_wellness"],
    equipmentRequired: ["gym_full", "dumbbells"],
    dayLabels: [
      { day: 1, label: "Full Body A", focus: "Присед, горизонтальный жим, тяга — базовая триада" },
      { day: 2, label: "Full Body B", focus: "Румынская тяга, вертикальный жим, подтягивания" },
      { day: 3, label: "Full Body C", focus: "Выпады, наклонный жим, тяга к поясу, изоляция" },
    ],
    benefits: [
      "Частая стимуляция всех мышечных групп — 3 раза в неделю",
      "Гибкий график — тренируйся через день",
      "Универсально для большинства целей",
    ],
    intensity: "moderate",
    targetSex: "any",
  },
  {
    id: "push_pull_legs_3x_condensed",
    name: "Push/Pull/Legs Condensed",
    russianName: "Жим-Тяга-Ноги 3 дня",
    description: "Адаптированный Push/Pull/Legs под 3 дня — концентрированная нагрузка",
    daysPerWeek: 3,
    minMinutes: 60,
    maxMinutes: 90,
    splitType: "push_pull_legs",
    experienceLevels: ["intermediate", "advanced"],
    goals: ["build_muscle", "strength", "athletic_body"],
    equipmentRequired: ["gym_full"],
    dayLabels: [
      { day: 1, label: "Push", focus: "Грудь, плечи, трицепс — все жимовые движения" },
      { day: 2, label: "Pull", focus: "Спина, задние дельты, бицепс — все тяговые" },
      { day: 3, label: "Legs", focus: "Квадрицепс, ягодицы, бицепс бедра, икры — полный низ" },
    ],
    benefits: [
      "Максимальный объём за одну тренировку каждой группы",
      "Полное восстановление между тренировками — 6-7 дней",
      "Подходит для набора массы при ограниченном времени",
    ],
    intensity: "high",
    targetSex: "any",
  },
  {
    id: "upper_lower_3x_hybrid",
    name: "Upper/Lower + Full Body",
    russianName: "Верх-Низ + Всё тело",
    description: "Гибрид: два акцента + одна полная тренировка",
    daysPerWeek: 3,
    minMinutes: 45,
    maxMinutes: 75,
    splitType: "upper_lower",
    experienceLevels: ["intermediate", "advanced"],
    goals: ["build_muscle", "strength", "athletic_body"],
    equipmentRequired: ["gym_full"],
    dayLabels: [
      { day: 1, label: "Upper Focus", focus: "Акцент на верх: грудь, спина, плечи, руки" },
      { day: 2, label: "Lower Focus", focus: "Акцент на низ: квадрицепс, ягодицы, бицепс бедра" },
      { day: 3, label: "Full Body", focus: "Лёгкая тренировка на всё тело или слабые места" },
    ],
    benefits: [
      "Больше упражнений на каждую зону",
      "Третий день для отстающих групп или лёгкой работы",
      "Универсальность и гибкость",
    ],
    intensity: "moderate",
    targetSex: "any",
  },
  {
    id: "full_body_3x_glutes_focus",
    name: "Full Body + Glutes Focus",
    russianName: "Всё тело + Ягодицы",
    description: "Три тренировки с дополнительным акцентом на ягодицы",
    daysPerWeek: 3,
    minMinutes: 45,
    maxMinutes: 75,
    splitType: "full_body",
    experienceLevels: ["intermediate", "advanced"],
    goals: ["lower_body_focus", "athletic_body", "build_muscle"],
    equipmentRequired: ["gym_full"],
    dayLabels: [
      { day: 1, label: "Full Body + Glutes A", focus: "База + акцент на ягодицы: ягодичный мост, отведения" },
      { day: 2, label: "Full Body General", focus: "Верх тела + базовые приседы" },
      { day: 3, label: "Full Body + Glutes B", focus: "База + акцент на ягодицы: выпады, румынская тяга" },
    ],
    benefits: [
      "Усиленная работа на ягодицы и ноги",
      "Сбалансированное развитие всего тела",
      "Идеально для женских целей",
    ],
    intensity: "moderate",
    targetSex: "female",
  },

  // ============= 4 ДНЯ В НЕДЕЛЮ =============
  {
    id: "upper_lower_4x_classic",
    name: "Upper/Lower Classic",
    russianName: "Верх-Низ классика",
    description: "Классический верх/низ — золотой стандарт",
    daysPerWeek: 4,
    minMinutes: 45,
    maxMinutes: 75,
    splitType: "upper_lower",
    experienceLevels: ["intermediate", "advanced"],
    goals: ["build_muscle", "strength", "athletic_body"],
    equipmentRequired: ["gym_full"],
    dayLabels: [
      { day: 1, label: "Upper A", focus: "Жимовые движения, горизонтальные тяги" },
      { day: 2, label: "Lower A", focus: "Приседания, румынская тяга, икры" },
      { day: 3, label: "Upper B", focus: "Вертикальный жим, подтягивания, изоляция рук" },
      { day: 4, label: "Lower B", focus: "Фронтальный присед, выпады, ягодичный мост" },
    ],
    benefits: [
      "Идеальный баланс объёма и восстановления",
      "Каждая группа тренируется 2 раза в неделю",
      "Один из самых эффективных сплитов для массы",
    ],
    intensity: "moderate",
    targetSex: "any",
  },
  {
    id: "upper_lower_4x_powerbuilding",
    name: "Powerbuilding 4x",
    russianName: "Сила + Масса",
    description: "Сила + масса — лучшее из двух миров",
    daysPerWeek: 4,
    minMinutes: 60,
    maxMinutes: 90,
    splitType: "upper_lower",
    experienceLevels: ["advanced"],
    goals: ["strength", "build_muscle"],
    equipmentRequired: ["gym_full"],
    dayLabels: [
      { day: 1, label: "Upper Power", focus: "Тяжёлые жимы и тяги 3-5 повторений" },
      { day: 2, label: "Lower Power", focus: "Тяжёлые приседы и тяги 3-5 повторений" },
      { day: 3, label: "Upper Hypertrophy", focus: "Объёмная работа 8-12 повторений" },
      { day: 4, label: "Lower Hypertrophy", focus: "Объёмная работа 8-12 повторений" },
    ],
    benefits: [
      "Развитие силы и массы одновременно",
      "Разнообразие тренировочных стимулов",
      "Для опытных атлетов с амбициями",
    ],
    intensity: "high",
    targetSex: "any",
  },
  {
    id: "full_body_4x_advanced",
    name: "Full Body Advanced",
    russianName: "Всё тело продвинутый",
    description: "Четыре тренировки на всё тело с разными акцентами",
    daysPerWeek: 4,
    minMinutes: 45,
    maxMinutes: 75,
    splitType: "full_body",
    experienceLevels: ["advanced"],
    goals: ["strength", "athletic_body", "build_muscle"],
    equipmentRequired: ["gym_full"],
    dayLabels: [
      { day: 1, label: "Strength", focus: "Тяжёлые базовые 3-5 повторений" },
      { day: 2, label: "Hypertrophy", focus: "Средний диапазон 8-12 повторений" },
      { day: 3, label: "Power", focus: "Взрывные движения и плиометрика" },
      { day: 4, label: "Volume", focus: "Высокообъёмная работа 12-15 повторений" },
    ],
    benefits: [
      "Разнообразие стимулов для максимального роста",
      "Частая практика всех движений — улучшение техники",
      "Подходит для спортсменов",
    ],
    intensity: "high",
    targetSex: "any",
  },
  {
    id: "upper_lower_4x_glutes",
    name: "Upper/Lower + Glutes",
    russianName: "Верх-Низ + Ягодицы",
    description: "Классический верх/низ с усиленным акцентом на ягодицы",
    daysPerWeek: 4,
    minMinutes: 45,
    maxMinutes: 75,
    splitType: "upper_lower",
    experienceLevels: ["intermediate", "advanced"],
    goals: ["lower_body_focus", "athletic_body", "build_muscle"],
    equipmentRequired: ["gym_full"],
    dayLabels: [
      { day: 1, label: "Upper Body", focus: "Грудь, спина, плечи, руки" },
      { day: 2, label: "Lower + Glutes A", focus: "Приседы, ягодичный мост, отведения" },
      { day: 3, label: "Upper Body", focus: "Другие углы и акценты на верх" },
      { day: 4, label: "Lower + Glutes B", focus: "Выпады, румынская, изоляция ягодиц" },
    ],
    benefits: [
      "Усиленная работа на нижнюю часть тела",
      "Ягодицы и ноги тренируются 2 раза в неделю",
      "Идеально для женских целей",
    ],
    intensity: "moderate",
    targetSex: "female",
  },

  // ============= 5 ДНЕЙ В НЕДЕЛЮ =============
  {
    id: "push_pull_legs_5x_classic",
    name: "Push/Pull/Legs",
    russianName: "Жим-Тяга-Ноги",
    description: "Проверенная схема для серьёзного роста",
    daysPerWeek: 5,
    minMinutes: 45,
    maxMinutes: 75,
    splitType: "push_pull_legs",
    experienceLevels: ["intermediate", "advanced"],
    goals: ["build_muscle", "strength", "athletic_body"],
    equipmentRequired: ["gym_full"],
    dayLabels: [
      { day: 1, label: "Push A", focus: "Грудь, передние дельты, трицепс" },
      { day: 2, label: "Pull A", focus: "Спина, задние дельты, бицепс" },
      { day: 3, label: "Legs A", focus: "Квадрицепсы, ягодицы, икры" },
      { day: 4, label: "Push B", focus: "Другие углы жимов" },
      { day: 5, label: "Pull B", focus: "Другие вариации тяг" },
    ],
    benefits: [
      "Максимальный объём на каждую группу",
      "Отличное восстановление — каждая группа отдыхает 2-3 дня",
      "Эффективно для набора массы",
    ],
    notes: "Требует хорошего восстановления и питания",
    intensity: "high",
    targetSex: "any",
  },
  {
    id: "upper_lower_legs_5x",
    name: "Upper/Lower/Legs Focus",
    russianName: "Верх-Низ-Ноги",
    description: "Верх, низ, и дополнительный день для ног и ягодиц",
    daysPerWeek: 5,
    minMinutes: 45,
    maxMinutes: 75,
    splitType: "upper_lower",
    experienceLevels: ["intermediate", "advanced"],
    goals: ["lower_body_focus", "build_muscle", "athletic_body"],
    equipmentRequired: ["gym_full"],
    dayLabels: [
      { day: 1, label: "Upper A", focus: "Жимы, тяги" },
      { day: 2, label: "Lower A", focus: "Приседания, румынская тяга" },
      { day: 3, label: "Upper B", focus: "Вариации жимов и тяг" },
      { day: 4, label: "Lower B", focus: "Выпады, ягодичный мост" },
      { day: 5, label: "Glutes & Legs", focus: "Полностью ягодицы и изоляция ног" },
    ],
    benefits: [
      "Усиленная работа на нижнюю часть — 3 дня в неделю",
      "Максимальный рост ягодиц и ног",
      "Идеально для акцента на нижнюю часть",
    ],
    intensity: "high",
    targetSex: "female",
  },
  {
    id: "push_pull_legs_5x_strength",
    name: "PPL Strength Focus",
    russianName: "Жим-Тяга-Ноги силовой",
    description: "Push/Pull/Legs с акцентом на силовые показатели",
    daysPerWeek: 5,
    minMinutes: 60,
    maxMinutes: 90,
    splitType: "push_pull_legs",
    experienceLevels: ["advanced"],
    goals: ["strength", "build_muscle"],
    equipmentRequired: ["gym_full"],
    dayLabels: [
      { day: 1, label: "Push Heavy", focus: "Тяжёлые жимы 3-5 повторений" },
      { day: 2, label: "Pull Heavy", focus: "Тяжёлые тяги 3-5 повторений" },
      { day: 3, label: "Legs Heavy", focus: "Тяжёлые приседы и тяги 3-5 повторений" },
      { day: 4, label: "Push Volume", focus: "Объёмная работа 8-12 повторений" },
      { day: 5, label: "Pull Volume", focus: "Объёмная работа 8-12 повторений" },
    ],
    benefits: [
      "Развитие силы и массы",
      "Разнообразие нагрузок",
      "Для тех, кто хочет больших весов",
    ],
    intensity: "high",
    targetSex: "any",
  },
  {
    id: "full_body_5x_athlete",
    name: "Athletic Performance",
    russianName: "Спортивная подготовка",
    description: "Пять тренировок для спортивной подготовки",
    daysPerWeek: 5,
    minMinutes: 45,
    maxMinutes: 75,
    splitType: "full_body",
    experienceLevels: ["advanced"],
    goals: ["athletic_body", "strength", "health_wellness"],
    equipmentRequired: ["gym_full"],
    dayLabels: [
      { day: 1, label: "Strength", focus: "Тяжёлые базовые движения" },
      { day: 2, label: "Power", focus: "Взрывные движения, плиометрика" },
      { day: 3, label: "Hypertrophy", focus: "Объёмная работа на мышцы" },
      { day: 4, label: "Conditioning", focus: "Выносливость и кондиция" },
      { day: 5, label: "Recovery", focus: "Лёгкая активность, мобильность" },
    ],
    benefits: [
      "Комплексное развитие атлетических качеств",
      "Улучшение всех аспектов физической формы",
      "Для спортсменов и продвинутых",
    ],
    intensity: "high",
    targetSex: "any",
  },

  // ============= 6 ДНЕЙ В НЕДЕЛЮ =============
  {
    id: "push_pull_legs_6x_classic",
    name: "PPL 6x Classic",
    russianName: "Жим-Тяга-Ноги 6 дней",
    description: "Два полных цикла Push/Pull/Legs — для продвинутых",
    daysPerWeek: 6,
    minMinutes: 45,
    maxMinutes: 75,
    splitType: "push_pull_legs",
    experienceLevels: ["advanced"],
    goals: ["build_muscle", "strength"],
    equipmentRequired: ["gym_full"],
    dayLabels: [
      { day: 1, label: "Push A", focus: "Тяжёлые жимы, акцент грудь" },
      { day: 2, label: "Pull A", focus: "Тяжёлые тяги, акцент спина" },
      { day: 3, label: "Legs A", focus: "Приседания, румынская тяга" },
      { day: 4, label: "Push B", focus: "Объёмная работа грудь и плечи" },
      { day: 5, label: "Pull B", focus: "Объёмная работа спина" },
      { day: 6, label: "Legs B", focus: "Фронтальные приседания, выпады" },
    ],
    benefits: [
      "Максимальная частота — каждая группа 2 раза в неделю",
      "Высокий объём тренировок",
      "Быстрые результаты при правильном восстановлении",
    ],
    notes: "Только для опытных с хорошим восстановлением",
    intensity: "high",
    targetSex: "any",
  },
  {
    id: "bro_split_6x",
    name: "Bro Split",
    russianName: "По группам мышц",
    description: "Каждый день — отдельная мышечная группа",
    daysPerWeek: 6,
    minMinutes: 45,
    maxMinutes: 75,
    splitType: "bro_split",
    experienceLevels: ["advanced"],
    goals: ["build_muscle"],
    equipmentRequired: ["gym_full"],
    dayLabels: [
      { day: 1, label: "Chest", focus: "Полностью грудь" },
      { day: 2, label: "Back", focus: "Полностью спина" },
      { day: 3, label: "Shoulders", focus: "Полностью плечи" },
      { day: 4, label: "Legs", focus: "Полностью ноги" },
      { day: 5, label: "Arms", focus: "Бицепс, трицепс" },
      { day: 6, label: "Glutes & Accessories", focus: "Ягодицы и дополнительная работа" },
    ],
    benefits: [
      "Максимальная концентрация на одной группе",
      "Высокий объём на каждую группу",
      "Классика бодибилдинга",
    ],
    notes: "Требует дисциплины и восстановления",
    intensity: "high",
    targetSex: "any",
  },
  {
    id: "upper_lower_6x_intensive",
    name: "Upper/Lower Intensive",
    russianName: "Верх-Низ интенсив",
    description: "Три цикла верх/низ — максимальная частота",
    daysPerWeek: 6,
    minMinutes: 45,
    maxMinutes: 75,
    splitType: "upper_lower",
    experienceLevels: ["advanced"],
    goals: ["build_muscle", "strength"],
    equipmentRequired: ["gym_full"],
    dayLabels: [
      { day: 1, label: "Upper Heavy", focus: "Тяжёлые жимы и тяги" },
      { day: 2, label: "Lower Heavy", focus: "Тяжёлые приседы и тяги" },
      { day: 3, label: "Upper Volume", focus: "Объёмная работа верх" },
      { day: 4, label: "Lower Volume", focus: "Объёмная работа низ" },
      { day: 5, label: "Upper Pump", focus: "Пампинг и изоляция" },
      { day: 6, label: "Lower Pump", focus: "Пампинг и изоляция" },
    ],
    benefits: [
      "Максимальная частота стимуляции",
      "Разнообразие нагрузок",
      "Очень высокий объём",
    ],
    intensity: "high",
    targetSex: "any",
  },
  {
    id: "push_pull_legs_6x_glutes",
    name: "PPL + Glutes Focus",
    russianName: "Жим-Тяга-Ноги + Ягодицы",
    description: "Push/Pull/Legs с дополнительным днём для ягодиц",
    daysPerWeek: 6,
    minMinutes: 45,
    maxMinutes: 75,
    splitType: "push_pull_legs",
    experienceLevels: ["advanced"],
    goals: ["lower_body_focus", "build_muscle"],
    equipmentRequired: ["gym_full"],
    dayLabels: [
      { day: 1, label: "Push", focus: "Грудь, плечи, трицепс" },
      { day: 2, label: "Pull", focus: "Спина, бицепс" },
      { day: 3, label: "Legs + Glutes A", focus: "Квадрицепсы, ягодицы" },
      { day: 4, label: "Push", focus: "Вариации жимов" },
      { day: 5, label: "Pull", focus: "Вариации тяг" },
      { day: 6, label: "Glutes + Hamstrings", focus: "Ягодицы, бицепс бедра, изоляция" },
    ],
    benefits: [
      "Максимальный фокус на ягодицы — 2 дня в неделю",
      "Сбалансированное развитие всего тела",
      "Идеально для женских амбиций",
    ],
    intensity: "high",
    targetSex: "female",
  },

  // ============= ДОПОЛНИТЕЛЬНЫЕ СПЕЦИАЛИЗИРОВАННЫЕ СХЕМЫ =============
  
  // Для похудения
  {
    id: "metabolic_conditioning_4x",
    name: "Metabolic Conditioning",
    russianName: "Метаболизм",
    description: "Высокоинтенсивная программа для жиросжигания",
    daysPerWeek: 4,
    minMinutes: 30,
    maxMinutes: 60,
    splitType: "full_body",
    experienceLevels: ["intermediate", "advanced"],
    goals: ["lose_weight", "athletic_body"],
    equipmentRequired: ["gym_full", "bodyweight"],
    dayLabels: [
      { day: 1, label: "Full Body HIIT", focus: "Высокоинтенсивные интервалы" },
      { day: 2, label: "Full Body Circuits", focus: "Круговая тренировка" },
      { day: 3, label: "Full Body Strength", focus: "Силовая с короткими отдыхами" },
      { day: 4, label: "Full Body Endurance", focus: "Выносливость и кондиция" },
    ],
    benefits: [
      "Максимальное жиросжигание",
      "Улучшение метаболизма",
      "Короткие интенсивные тренировки",
    ],
    intensity: "high",
    targetSex: "any",
  },

  // Для минимального времени
  {
    id: "express_4x",
    name: "Express 4x",
    russianName: "Экспресс 4 дня",
    description: "Эффективные короткие тренировки для занятых",
    daysPerWeek: 4,
    minMinutes: 30,
    maxMinutes: 45,
    splitType: "upper_lower",
    experienceLevels: ["intermediate", "advanced"],
    goals: ["health_wellness", "athletic_body", "build_muscle"],
    equipmentRequired: ["gym_full"],
    dayLabels: [
      { day: 1, label: "Upper Compound", focus: "Только базовые упражнения верх" },
      { day: 2, label: "Lower Compound", focus: "Только базовые упражнения низ" },
      { day: 3, label: "Upper Compound", focus: "Другие базовые верх" },
      { day: 4, label: "Lower Compound", focus: "Другие базовые низ" },
    ],
    benefits: [
      "Максимум результата за минимум времени",
      "Только самые эффективные упражнения",
      "Подходит для занятых людей",
    ],
    intensity: "moderate",
    targetSex: "any",
  },

  // Для здоровья и долголетия
  {
    id: "longevity_3x",
    name: "Longevity Program",
    russianName: "Здоровье и долголетие",
    description: "Программа для здоровья, мобильности и долголетия",
    daysPerWeek: 3,
    minMinutes: 45,
    maxMinutes: 60,
    splitType: "full_body",
    experienceLevels: ["beginner", "beginner", "intermediate"],
    goals: ["health_wellness"],
    equipmentRequired: ["gym_full", "bodyweight"],
    dayLabels: [
      { day: 1, label: "Strength & Mobility", focus: "Силовые + растяжка и мобильность" },
      { day: 2, label: "Functional Fitness", focus: "Функциональные движения для жизни" },
      { day: 3, label: "Balance & Core", focus: "Баланс, координация, кор" },
    ],
    benefits: [
      "Фокус на здоровье суставов и связок",
      "Улучшение качества жизни",
      "Профилактика травм и болезней",
    ],
    intensity: "low",
    targetSex: "any",
  },

  // ============= ДОПОЛНИТЕЛЬНЫЕ СХЕМЫ ДЛЯ ПОЛНОГО ПОКРЫТИЯ =============
  
  // Новичкам на 4 дня
  {
    id: "full_body_4x_beginner",
    name: "Full Body Beginner 4x",
    russianName: "Новичок 4 дня",
    description: "Четыре тренировки для новичков с комфортной нагрузкой",
    daysPerWeek: 4,
    minMinutes: 40,
    maxMinutes: 60,
    splitType: "full_body",
    experienceLevels: ["beginner"],
    goals: ["build_muscle", "athletic_body", "health_wellness"],
    equipmentRequired: ["gym_full", "dumbbells"],
    dayLabels: [
      { day: 1, label: "Full Body A", focus: "Базовые движения: присед, жим, тяга" },
      { day: 2, label: "Full Body B", focus: "Другие углы: выпады, жим под углом, тяга к поясу" },
      { day: 3, label: "Full Body C", focus: "Лёгкая тренировка: мышцы кора и стабилизаторы" },
      { day: 4, label: "Full Body D", focus: "Повторение базы с меньшими весами" },
    ],
    benefits: [
      "Частая практика движений — быстрое освоение техники",
      "Мягкая прогрессия нагрузки для новичков",
      "Достаточно восстановления между тренировками",
    ],
    intensity: "low",
    targetSex: "any",
  },

  // Жиросжигание для новичков на 3 дня
  {
    id: "fat_loss_3x_beginner",
    name: "Fat Loss Beginner",
    russianName: "Сжигание жира",
    description: "Эффективная программа жиросжигания для начинающих",
    daysPerWeek: 3,
    minMinutes: 40,
    maxMinutes: 60,
    splitType: "full_body",
    experienceLevels: ["beginner"],
    goals: ["lose_weight", "health_wellness", "athletic_body"],
    equipmentRequired: ["gym_full", "bodyweight"],
    dayLabels: [
      { day: 1, label: "Strength + Cardio", focus: "Базовые силовые + лёгкое кардио" },
      { day: 2, label: "Circuit Training", focus: "Круговая тренировка на всё тело" },
      { day: 3, label: "Full Body Conditioning", focus: "Функциональные движения для жиросжигания" },
    ],
    benefits: [
      "Максимальное жиросжигание при комфортной интенсивности",
      "Улучшение выносливости и метаболизма",
      "Безопасно для новичков",
    ],
    intensity: "moderate",
    targetSex: "any",
  },

  // Жиросжигание для intermediate на 5 дней
  {
    id: "fat_loss_5x_intermediate",
    name: "Fat Loss Intensive",
    russianName: "Интенсивное жиросжигание",
    description: "Интенсивная программа жиросжигания с высокой частотой",
    daysPerWeek: 5,
    minMinutes: 40,
    maxMinutes: 60,
    splitType: "full_body",
    experienceLevels: ["intermediate"],
    goals: ["lose_weight", "athletic_body"],
    equipmentRequired: ["gym_full", "bodyweight"],
    dayLabels: [
      { day: 1, label: "HIIT Upper", focus: "Высокоинтенсивная работа на верх тела" },
      { day: 2, label: "HIIT Lower", focus: "Высокоинтенсивная работа на низ тела" },
      { day: 3, label: "Metabolic Circuits", focus: "Круговые тренировки для метаболизма" },
      { day: 4, label: "Strength Endurance", focus: "Силовая выносливость" },
      { day: 5, label: "Active Recovery", focus: "Активное восстановление и кардио" },
    ],
    benefits: [
      "Максимальное жиросжигание — 5 тренировок в неделю",
      "Разнообразие форматов тренировок",
      "Быстрые результаты при правильном питании",
    ],
    intensity: "high",
    targetSex: "any",
  },

  // PPL для intermediate на 6 дней
  {
    id: "push_pull_legs_6x_intermediate",
    name: "PPL 6x Intermediate",
    russianName: "Жим-Тяга-Ноги 6 дней",
    description: "Push/Pull/Legs для среднего уровня — высокая частота тренировок",
    daysPerWeek: 6,
    minMinutes: 45,
    maxMinutes: 75,
    splitType: "push_pull_legs",
    experienceLevels: ["intermediate"],
    goals: ["build_muscle", "strength", "athletic_body"],
    equipmentRequired: ["gym_full"],
    dayLabels: [
      { day: 1, label: "Push A", focus: "Грудь и передние дельты, средняя интенсивность" },
      { day: 2, label: "Pull A", focus: "Спина и бицепс, средняя интенсивность" },
      { day: 3, label: "Legs A", focus: "Квадрицепсы и ягодицы" },
      { day: 4, label: "Push B", focus: "Плечи и трицепс, больше изоляции" },
      { day: 5, label: "Pull B", focus: "Спина и задние дельты, больше изоляции" },
      { day: 6, label: "Legs B", focus: "Бицепс бедра и икры" },
    ],
    benefits: [
      "Высокая частота — каждая группа 2 раза в неделю",
      "Оптимально для набора массы среднего уровня",
      "Разнообразие упражнений и углов работы",
    ],
    notes: "Требует хорошего восстановления и питания",
    intensity: "high",
    targetSex: "any",
  },

  // Strength для новичков на 3 дня
  {
    id: "strength_3x_beginner",
    name: "Strength Basics",
    russianName: "Основы силы",
    description: "Базовая силовая программа для новичков",
    daysPerWeek: 3,
    minMinutes: 45,
    maxMinutes: 75,
    splitType: "full_body",
    experienceLevels: ["beginner"],
    goals: ["strength", "build_muscle", "athletic_body"],
    equipmentRequired: ["gym_full"],
    dayLabels: [
      { day: 1, label: "Squat Focus", focus: "Приседания + жимы" },
      { day: 2, label: "Deadlift Focus", focus: "Становая тяга + подтягивания" },
      { day: 3, label: "Bench Focus", focus: "Жим лёжа + приседания" },
    ],
    benefits: [
      "Фокус на 3 базовых движениях",
      "Развитие силы и техники",
      "Простая и эффективная схема",
    ],
    intensity: "moderate",
    targetSex: "any",
  },
];
