-- Загрузка всех 26 схем тренировок (с TEXT id)
TRUNCATE TABLE workout_schemes CASCADE;

-- 2 дня (2 схемы)
INSERT INTO workout_schemes (id, name, description, days_per_week, min_minutes, max_minutes, split_type, experience_levels, goals, equipment_required, day_labels, benefits, notes, intensity, target_sex) VALUES
('full_body_2x_beginner', 'Full Body Starter', 'Две базовые тренировки на всё тело — идеальный старт для новичков', 2, 30, 60, 'full_body', ARRAY['never_trained'], ARRAY['health_wellness', 'lose_weight', 'athletic_body'], ARRAY['gym_full', 'dumbbells', 'bodyweight'], '[{"day": 1, "label": "Full Body A", "focus": "Базовые движения: приседания, жимы, тяги на все тело"},{"day": 2, "label": "Full Body B", "focus": "Вариации базы с фокусом на другие углы и мышцы"}]'::jsonb, ARRAY['Простая структура — легко запомнить','Комфортное восстановление — 2-3 дня между тренировками','Каждая мышца работает 2 раза в неделю — оптимально для роста'], 'Подходит для тех, кто только начинает свой фитнес-путь', 'low', 'any'),
('full_body_2x_recovery', 'Full Body Recovery', 'Восстановительная программа после долгого перерыва', 2, 30, 60, 'full_body', ARRAY['long_break'], ARRAY['health_wellness', 'lose_weight'], ARRAY['gym_full', 'dumbbells'], '[{"day": 1, "label": "Full Body Gentle", "focus": "Мягкая нагрузка, восстановление техники"},{"day": 2, "label": "Full Body Rebuild", "focus": "Постепенное увеличение интенсивности"}]'::jsonb, ARRAY['Щадящая нагрузка для восстановления после перерыва','Фокус на технике и нейромышечной связи','Минимальный риск травм и перетренированности'], NULL, 'low', 'any');

-- 3 дня (5 схем)
INSERT INTO workout_schemes (id, name, description, days_per_week, min_minutes, max_minutes, split_type, experience_levels, goals, equipment_required, day_labels, benefits, intensity, target_sex) VALUES
('full_body_3x_classic', 'Full Body Classic', 'Классика — три полноценные тренировки на всё тело', 3, 45, 75, 'full_body', ARRAY['never_trained', 'long_break', 'training_regularly'], ARRAY['build_muscle', 'athletic_body', 'lose_weight', 'health_wellness'], ARRAY['gym_full', 'dumbbells'], '[{"day": 1, "label": "Full Body A", "focus": "Присед, горизонтальный жим, тяга — базовая триада"},{"day": 2, "label": "Full Body B", "focus": "Румынская тяга, вертикальный жим, подтягивания"},{"day": 3, "label": "Full Body C", "focus": "Выпады, наклонный жим, тяга к поясу, изоляция"}]'::jsonb, ARRAY['Частая стимуляция всех мышечных групп — 3 раза в неделю','Гибкий график — тренируйся через день','Универсально для большинства целей'], 'moderate', 'any'),
('push_pull_legs_3x_condensed', 'Push/Pull/Legs Condensed', 'Адаптированный Push/Pull/Legs под 3 дня — концентрированная нагрузка', 3, 60, 90, 'push_pull_legs', ARRAY['training_regularly', 'training_experienced'], ARRAY['build_muscle', 'strength', 'athletic_body'], ARRAY['gym_full'], '[{"day": 1, "label": "Push", "focus": "Грудь, плечи, трицепс — все жимовые движения"},{"day": 2, "label": "Pull", "focus": "Спина, задние дельты, бицепс — все тяговые"},{"day": 3, "label": "Legs", "focus": "Квадрицепс, ягодицы, бицепс бедра, икры — полный низ"}]'::jsonb, ARRAY['Максимальный объём за одну тренировку каждой группы','Полное восстановление между тренировками — 6-7 дней','Подходит для набора массы при ограниченном времени'], 'high', 'any'),
('upper_lower_3x_hybrid', 'Upper/Lower + Full Body', 'Гибрид: два акцента + одна полная тренировка', 3, 45, 75, 'upper_lower', ARRAY['training_regularly', 'training_experienced'], ARRAY['build_muscle', 'strength', 'athletic_body'], ARRAY['gym_full'], '[{"day": 1, "label": "Upper Focus", "focus": "Акцент на верх: грудь, спина, плечи, руки"},{"day": 2, "label": "Lower Focus", "focus": "Акцент на низ: квадрицепс, ягодицы, бицепс бедра"},{"day": 3, "label": "Full Body", "focus": "Лёгкая тренировка на всё тело или слабые места"}]'::jsonb, ARRAY['Больше упражнений на каждую зону','Третий день для отстающих групп или лёгкой работы','Универсальность и гибкость'], 'moderate', 'any'),
('full_body_3x_glutes_focus', 'Full Body + Glutes Focus', 'Три тренировки с дополнительным акцентом на ягодицы', 3, 45, 75, 'full_body', ARRAY['training_regularly', 'training_experienced'], ARRAY['lower_body_focus', 'athletic_body', 'build_muscle'], ARRAY['gym_full'], '[{"day": 1, "label": "Full Body + Glutes A", "focus": "База + акцент на ягодицы: ягодичный мост, отведения"},{"day": 2, "label": "Full Body General", "focus": "Верх тела + базовые приседы"},{"day": 3, "label": "Full Body + Glutes B", "focus": "База + акцент на ягодицы: выпады, румынская тяга"}]'::jsonb, ARRAY['Усиленная работа на ягодицы и ноги','Сбалансированное развитие всего тела','Идеально для женских целей'], 'moderate', 'female'),
('longevity_3x', 'Longevity Program', 'Программа для здоровья, мобильности и долголетия', 3, 45, 60, 'full_body', ARRAY['never_trained', 'long_break', 'training_regularly'], ARRAY['health_wellness'], ARRAY['gym_full', 'bodyweight'], '[{"day": 1, "label": "Strength & Mobility", "focus": "Силовые + растяжка и мобильность"},{"day": 2, "label": "Functional Fitness", "focus": "Функциональные движения для жизни"},{"day": 3, "label": "Balance & Core", "focus": "Баланс, координация, кор"}]'::jsonb, ARRAY['Фокус на здоровье суставов и связок','Улучшение качества жизни','Профилактика травм и болезней'], 'low', 'any');

-- 4 дня (6 схем)
INSERT INTO workout_schemes (id, name, description, days_per_week, min_minutes, max_minutes, split_type, experience_levels, goals, equipment_required, day_labels, benefits, intensity, target_sex) VALUES
('upper_lower_4x_classic', 'Upper/Lower Classic', 'Классический верх/низ — золотой стандарт', 4, 45, 75, 'upper_lower', ARRAY['training_regularly', 'training_experienced'], ARRAY['build_muscle', 'strength', 'athletic_body'], ARRAY['gym_full'], '[{"day": 1, "label": "Upper A", "focus": "Жимовые движения, горизонтальные тяги"},{"day": 2, "label": "Lower A", "focus": "Приседания, румынская тяга, икры"},{"day": 3, "label": "Upper B", "focus": "Вертикальный жим, подтягивания, изоляция рук"},{"day": 4, "label": "Lower B", "focus": "Фронтальный присед, выпады, ягодичный мост"}]'::jsonb, ARRAY['Идеальный баланс объёма и восстановления','Каждая группа тренируется 2 раза в неделю','Один из самых эффективных сплитов для массы'], 'moderate', 'any'),
('upper_lower_4x_powerbuilding', 'Powerbuilding 4x', 'Сила + масса — лучшее из двух миров', 4, 60, 90, 'upper_lower', ARRAY['training_experienced'], ARRAY['strength', 'build_muscle'], ARRAY['gym_full'], '[{"day": 1, "label": "Upper Power", "focus": "Тяжёлые жимы и тяги 3-5 повторений"},{"day": 2, "label": "Lower Power", "focus": "Тяжёлые приседы и тяги 3-5 повторений"},{"day": 3, "label": "Upper Hypertrophy", "focus": "Объёмная работа 8-12 повторений"},{"day": 4, "label": "Lower Hypertrophy", "focus": "Объёмная работа 8-12 повторений"}]'::jsonb, ARRAY['Развитие силы и массы одновременно','Разнообразие тренировочных стимулов','Для опытных атлетов с амбициями'], 'high', 'any'),
('full_body_4x_advanced', 'Full Body Advanced', 'Четыре тренировки на всё тело с разными акцентами', 4, 45, 75, 'full_body', ARRAY['training_experienced'], ARRAY['strength', 'athletic_body', 'build_muscle'], ARRAY['gym_full'], '[{"day": 1, "label": "Strength", "focus": "Тяжёлые базовые 3-5 повторений"},{"day": 2, "label": "Hypertrophy", "focus": "Средний диапазон 8-12 повторений"},{"day": 3, "label": "Power", "focus": "Взрывные движения и плиометрика"},{"day": 4, "label": "Volume", "focus": "Высокообъёмная работа 12-15 повторений"}]'::jsonb, ARRAY['Разнообразие стимулов для максимального роста','Частая практика всех движений — улучшение техники','Подходит для спортсменов'], 'high', 'any'),
('upper_lower_4x_glutes', 'Upper/Lower + Glutes', 'Классический верх/низ с усиленным акцентом на ягодицы', 4, 45, 75, 'upper_lower', ARRAY['training_regularly', 'training_experienced'], ARRAY['lower_body_focus', 'athletic_body', 'build_muscle'], ARRAY['gym_full'], '[{"day": 1, "label": "Upper Body", "focus": "Грудь, спина, плечи, руки"},{"day": 2, "label": "Lower + Glutes A", "focus": "Приседы, ягодичный мост, отведения"},{"day": 3, "label": "Upper Body", "focus": "Другие углы и акценты на верх"},{"day": 4, "label": "Lower + Glutes B", "focus": "Выпады, румынская, изоляция ягодиц"}]'::jsonb, ARRAY['Усиленная работа на нижнюю часть тела','Ягодицы и ноги тренируются 2 раза в неделю','Идеально для женских целей'], 'moderate', 'female'),
('metabolic_conditioning_4x', 'Metabolic Conditioning', 'Высокоинтенсивная программа для жиросжигания', 4, 30, 60, 'full_body', ARRAY['training_regularly', 'training_experienced'], ARRAY['lose_weight', 'athletic_body'], ARRAY['gym_full', 'bodyweight'], '[{"day": 1, "label": "Full Body HIIT", "focus": "Высокоинтенсивные интервалы"},{"day": 2, "label": "Full Body Circuits", "focus": "Круговая тренировка"},{"day": 3, "label": "Full Body Strength", "focus": "Силовая с короткими отдыхами"},{"day": 4, "label": "Full Body Endurance", "focus": "Выносливость и кондиция"}]'::jsonb, ARRAY['Максимальное жиросжигание','Улучшение метаболизма','Короткие интенсивные тренировки'], 'high', 'any'),
('express_4x', 'Express 4x', 'Эффективные короткие тренировки для занятых', 4, 30, 45, 'upper_lower', ARRAY['training_regularly', 'training_experienced'], ARRAY['health_wellness', 'athletic_body', 'build_muscle'], ARRAY['gym_full'], '[{"day": 1, "label": "Upper Compound", "focus": "Только базовые упражнения верх"},{"day": 2, "label": "Lower Compound", "focus": "Только базовые упражнения низ"},{"day": 3, "label": "Upper Compound", "focus": "Другие базовые верх"},{"day": 4, "label": "Lower Compound", "focus": "Другие базовые низ"}]'::jsonb, ARRAY['Максимум результата за минимум времени','Только самые эффективные упражнения','Подходит для занятых людей'], 'moderate', 'any');

-- 5 дней (4 схемы)
INSERT INTO workout_schemes (id, name, description, days_per_week, min_minutes, max_minutes, split_type, experience_levels, goals, equipment_required, day_labels, benefits, notes, intensity, target_sex) VALUES
('push_pull_legs_5x_classic', 'Push/Pull/Legs', 'Проверенная схема для серьёзного роста', 5, 45, 75, 'push_pull_legs', ARRAY['training_regularly', 'training_experienced'], ARRAY['build_muscle', 'strength', 'athletic_body'], ARRAY['gym_full'], '[{"day": 1, "label": "Push A", "focus": "Грудь, передние дельты, трицепс"},{"day": 2, "label": "Pull A", "focus": "Спина, задние дельты, бицепс"},{"day": 3, "label": "Legs A", "focus": "Квадрицепсы, ягодицы, икры"},{"day": 4, "label": "Push B", "focus": "Другие углы жимов"},{"day": 5, "label": "Pull B", "focus": "Другие вариации тяг"}]'::jsonb, ARRAY['Максимальный объём на каждую группу','Отличное восстановление — каждая группа отдыхает 2-3 дня','Эффективно для набора массы'], 'Требует хорошего восстановления и питания', 'high', 'any'),
('upper_lower_legs_5x', 'Upper/Lower/Legs Focus', 'Верх, низ, и дополнительный день для ног и ягодиц', 5, 45, 75, 'upper_lower', ARRAY['training_regularly', 'training_experienced'], ARRAY['lower_body_focus', 'build_muscle', 'athletic_body'], ARRAY['gym_full'], '[{"day": 1, "label": "Upper A", "focus": "Жимы, тяги"},{"day": 2, "label": "Lower A", "focus": "Приседания, румынская тяга"},{"day": 3, "label": "Upper B", "focus": "Вариации жимов и тяг"},{"day": 4, "label": "Lower B", "focus": "Выпады, ягодичный мост"},{"day": 5, "label": "Glutes & Legs", "focus": "Полностью ягодицы и изоляция ног"}]'::jsonb, ARRAY['Усиленная работа на нижнюю часть — 3 дня в неделю','Максимальный рост ягодиц и ног','Идеально для акцента на нижнюю часть'], NULL, 'high', 'female'),
('push_pull_legs_5x_strength', 'PPL Strength Focus', 'Push/Pull/Legs с акцентом на силовые показатели', 5, 60, 90, 'push_pull_legs', ARRAY['training_experienced'], ARRAY['strength', 'build_muscle'], ARRAY['gym_full'], '[{"day": 1, "label": "Push Heavy", "focus": "Тяжёлые жимы 3-5 повторений"},{"day": 2, "label": "Pull Heavy", "focus": "Тяжёлые тяги 3-5 повторений"},{"day": 3, "label": "Legs Heavy", "focus": "Тяжёлые приседы и тяги 3-5 повторений"},{"day": 4, "label": "Push Volume", "focus": "Объёмная работа 8-12 повторений"},{"day": 5, "label": "Pull Volume", "focus": "Объёмная работа 8-12 повторений"}]'::jsonb, ARRAY['Развитие силы и массы','Разнообразие нагрузок','Для тех, кто хочет больших весов'], NULL, 'high', 'any'),
('full_body_5x_athlete', 'Athletic Performance', 'Пять тренировок для спортивной подготовки', 5, 45, 75, 'full_body', ARRAY['training_experienced'], ARRAY['athletic_body', 'strength', 'health_wellness'], ARRAY['gym_full'], '[{"day": 1, "label": "Strength", "focus": "Тяжёлые базовые движения"},{"day": 2, "label": "Power", "focus": "Взрывные движения, плиометрика"},{"day": 3, "label": "Hypertrophy", "focus": "Объёмная работа на мышцы"},{"day": 4, "label": "Conditioning", "focus": "Выносливость и кондиция"},{"day": 5, "label": "Recovery", "focus": "Лёгкая активность, мобильность"}]'::jsonb, ARRAY['Комплексное развитие атлетических качеств','Улучшение всех аспектов физической формы','Для спортсменов и продвинутых'], NULL, 'high', 'any');

-- 6 дней (4 схемы)
INSERT INTO workout_schemes (id, name, description, days_per_week, min_minutes, max_minutes, split_type, experience_levels, goals, equipment_required, day_labels, benefits, notes, intensity, target_sex) VALUES
('push_pull_legs_6x_classic', 'PPL 6x Classic', 'Два полных цикла Push/Pull/Legs — для продвинутых', 6, 45, 75, 'push_pull_legs', ARRAY['training_experienced'], ARRAY['build_muscle', 'strength'], ARRAY['gym_full'], '[{"day": 1, "label": "Push A", "focus": "Тяжёлые жимы, акцент грудь"},{"day": 2, "label": "Pull A", "focus": "Тяжёлые тяги, акцент спина"},{"day": 3, "label": "Legs A", "focus": "Приседания, румынская тяга"},{"day": 4, "label": "Push B", "focus": "Объёмная работа грудь и плечи"},{"day": 5, "label": "Pull B", "focus": "Объёмная работа спина"},{"day": 6, "label": "Legs B", "focus": "Фронтальные приседания, выпады"}]'::jsonb, ARRAY['Максимальная частота — каждая группа 2 раза в неделю','Высокий объём тренировок','Быстрые результаты при правильном восстановлении'], 'Только для опытных с хорошим восстановлением', 'high', 'any'),
('bro_split_6x', 'Bro Split', 'Каждый день — отдельная мышечная группа', 6, 45, 75, 'bro_split', ARRAY['training_experienced'], ARRAY['build_muscle'], ARRAY['gym_full'], '[{"day": 1, "label": "Chest", "focus": "Полностью грудь"},{"day": 2, "label": "Back", "focus": "Полностью спина"},{"day": 3, "label": "Shoulders", "focus": "Полностью плечи"},{"day": 4, "label": "Legs", "focus": "Полностью ноги"},{"day": 5, "label": "Arms", "focus": "Бицепс, трицепс"},{"day": 6, "label": "Glutes & Accessories", "focus": "Ягодицы и дополнительная работа"}]'::jsonb, ARRAY['Максимальная концентрация на одной группе','Высокий объём на каждую группу','Классика бодибилдинга'], 'Требует дисциплины и восстановления', 'high', 'any'),
('upper_lower_6x_intensive', 'Upper/Lower Intensive', 'Три цикла верх/низ — максимальная частота', 6, 45, 75, 'upper_lower', ARRAY['training_experienced'], ARRAY['build_muscle', 'strength'], ARRAY['gym_full'], '[{"day": 1, "label": "Upper Heavy", "focus": "Тяжёлые жимы и тяги"},{"day": 2, "label": "Lower Heavy", "focus": "Тяжёлые приседы и тяги"},{"day": 3, "label": "Upper Volume", "focus": "Объёмная работа верх"},{"day": 4, "label": "Lower Volume", "focus": "Объёмная работа низ"},{"day": 5, "label": "Upper Pump", "focus": "Пампинг и изоляция"},{"day": 6, "label": "Lower Pump", "focus": "Пампинг и изоляция"}]'::jsonb, ARRAY['Максимальная частота стимуляции','Разнообразие нагрузок','Очень высокий объём'], NULL, 'high', 'any'),
('push_pull_legs_6x_glutes', 'PPL + Glutes Focus', 'Push/Pull/Legs с дополнительным днём для ягодиц', 6, 45, 75, 'push_pull_legs', ARRAY['training_experienced'], ARRAY['lower_body_focus', 'build_muscle'], ARRAY['gym_full'], '[{"day": 1, "label": "Push", "focus": "Грудь, плечи, трицепс"},{"day": 2, "label": "Pull", "focus": "Спина, бицепс"},{"day": 3, "label": "Legs + Glutes A", "focus": "Квадрицепсы, ягодицы"},{"day": 4, "label": "Push", "focus": "Вариации жимов"},{"day": 5, "label": "Pull", "focus": "Вариации тяг"},{"day": 6, "label": "Glutes + Hamstrings", "focus": "Ягодицы, бицепс бедра, изоляция"}]'::jsonb, ARRAY['Максимальный фокус на ягодицы — 2 дня в неделю','Сбалансированное развитие всего тела','Идеально для женских амбиций'], NULL, 'high', 'female');

-- Подтверждение
SELECT 'Схемы загружены!' as status, COUNT(*) as total FROM workout_schemes;
